name: Run build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:

  run-build-ubuntu:
    runs-on: ubuntu-20.04
    timeout-minutes: 75
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Get Version
        run: |
          VER=$(cat VERSION)
          echo "V_VERSION=$VER" >> $GITHUB_ENV

      - name: Create PRs for wrapper repositories
        run: |
          ./.github/workflows/create_auto_pr.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
