name: Run build
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:

  run-build-ubuntu:
    runs-on: ubuntu-20.04
    timeout-minutes: 75
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Get Version
        run: |
          VER=$(cat VERSION)
          echo "V_VERSION=$VER" >> $GITHUB_ENV

      - name: Create PRs for wrapper repositories
        run: |
          new_cpp_version=${{ env.V_VERSION }}
          for repo in wrapperbuild wrapperbuild1; do
            cd $repo
            git add conanfile.py build.yml
            git commit -m "Update client-cpp version to $new_cpp_version"
            git checkout -b update-client-cpp-version
            git push --set-upstream origin update-client-cpp-version
            gh pr create --base main --head update-client-cpp-version --title "Update client-cpp version to $new_cpp_version" --body "Automated PR created by GitHub Actions"
            cd ..
          done
