name: Run build
on:
  create:
jobs:
  run-build-ubuntu:
    if: ${{ contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        wrapper_repos: [ mustyantsev/wrapperbuild, mustyantsev/wrapperbuild2 ]
    env:
      ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
      ACTIONS_RUNNER_DEBUG: ${{ secrets.ACTIONS_RUNNER_DEBUG }}
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    timeout-minutes: 75
    steps:
      - name: Checkout the ${{ matrix.wrapper_repos }} wrapper_repos
        uses: actions/checkout@master
        with:
          repository: ${{ matrix.wrapper_repos }}
          path: wrapper_repos
          fetch-depth: 0
      - name: LS dirs
        run: |
          ls

#      - name: Create PRs for wrapper repositories
#        run: |
#          ./.github/workflows/create_auto_pr.sh
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
