name: Client-CPP update
on:
  schedule:
    - cron: "0 7 * * 1"

  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  client-cpp-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check new Client-CPP version
        run: |
          NEW_VERSION=$(gh api repos/opentdf/client-cpp/releases/latest -q '.tag_name')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Check current Client-CPP version
        run: |
          CURRENT_VERSION=$(grep 'self.requires("opentdf-client/' < main-src/conanfile.py | awk -F 'opentdf-client/' '{print $2}' | awk -F '@' '{print $1}')
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Check if update branch already exists
        run: |
          BRANCH_NAME="automatic-update-to-client-cpp-${{ env.NEW_VERSION }}"
          BRANCH_EXISTS=$(git ls-remote --heads origin $BRANCH_NAME)
          echo "BRANCH_EXISTS=$BRANCH_EXISTS" >> $GITHUB_ENV

      - name: Update to new version
        if: ${{ env.BRANCH_EXISTS == '' }} || ${{ env.NEW_VERSION != env.CURRENT_VERSION }}
        run: |
          ./.github/workflows/create_auto_pr.sh
